from pathlib import Path
from datetime import datetime, timezone

from OCP.STEPControl import STEPControl_Reader
from OCP.IFSelect import IFSelect_ReturnStatus
from OCP.TopExp import TopExp_Explorer
from OCP.TopAbs import TopAbs_ShapeEnum


PROJECT_ROOT = Path(__file__).resolve().parents[1]
STEP_FILE = PROJECT_ROOT / "01_Geometry" / "engine_mount_bracket.step"
REPORT_FILE = PROJECT_ROOT / "01_Geometry" / "geometry_import_report.txt"


def count_shapes(shape, shape_type):
    """Count shapes of a specified OpenCascade type."""
    explorer = TopExp_Explorer(shape, shape_type)
    count = 0

    while explorer.More():
        count += 1
        explorer.Next()

    return count


def main():
    print("=" * 60)
    print("AUTOMOTIVE ENGINE MOUNT - STEP GEOMETRY IMPORT")
    print("=" * 60)

    print(f"\nSTEP file: {STEP_FILE}")

    if not STEP_FILE.exists():
        print("\nERROR: STEP file not found.")
        print(f"Expected location: {STEP_FILE}")
        return 1

    try:
        reader = STEPControl_Reader()

        print("\nReading STEP geometry...")

        status = reader.ReadFile(str(STEP_FILE))

        if status != IFSelect_ReturnStatus.IFSelect_RetDone:
            print(f"ERROR: STEP file could not be read. Status: {status}")
            return 1

        print("STEP file read successfully.")

        transferred = reader.TransferRoots()

        if not transferred:
            print("ERROR: STEP geometry could not be transferred.")
            return 1

        shape = reader.OneShape()

        if shape.IsNull():
            print("ERROR: Imported geometry is null.")
            return 1

        # Count geometric entities
        solids = count_shapes(
            shape,
            TopAbs_ShapeEnum.TopAbs_SOLID
        )

        shells = count_shapes(
            shape,
            TopAbs_ShapeEnum.TopAbs_SHELL
        )

        faces = count_shapes(
            shape,
            TopAbs_ShapeEnum.TopAbs_FACE
        )

        edges = count_shapes(
            shape,
            TopAbs_ShapeEnum.TopAbs_EDGE
        )

        vertices = count_shapes(
            shape,
            TopAbs_ShapeEnum.TopAbs_VERTEX
        )

        timestamp = datetime.now(timezone.utc).isoformat()

        report = f"""
AUTOMOTIVE ENGINE MOUNT FEA
STEP GEOMETRY IMPORT REPORT
========================================

Generated UTC:
{timestamp}

Input file:
{STEP_FILE}

Import status:
SUCCESS

Geometry statistics:
--------------------
Solids   : {solids}
Shells   : {shells}
Faces    : {faces}
Edges    : {edges}
Vertices : {vertices}

Notes:
------
- Geometry was imported using OpenCascade STEPControl.
- Original STEP file was not modified.
- These values describe the imported CAD topology.
- No FEA solver results are generated by this script.
"""

        REPORT_FILE.write_text(report.strip() + "\n", encoding="utf-8")

        print("\nGeometry imported successfully.")
        print("\nGeometry statistics:")
        print(f"  Solids   : {solids}")
        print(f"  Shells   : {shells}")
        print(f"  Faces    : {faces}")
        print(f"  Edges    : {edges}")
        print(f"  Vertices : {vertices}")

        print(f"\nReport saved to:")
        print(REPORT_FILE)

        return 0

    except Exception as exc:
        print("\nERROR during STEP import:")
        print(exc)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())